### ISSUE TITLE
Update the website for 4.0.0 release

### ISSUE THREAD

**Issue by berezovskyi** [OSLC/developing-oslc-applications#28]
Shall we update the website for the upcoming release? At least in a pull request.

See the forum post draft for tomorrow: https://hackmd.io/QEK5pMnJQZK3sz9IT0I7Kg. There I specifically write:

> - Explore the newly consolidated [Lyo documentation](https://oslc.github.io/developing-oslc-applications/eclipse_lyo/eclipse-lyo.html) as well as [4.0.0.RC Javadocs](https://download.eclipse.org/lyo/docs/all/4.0.0.RC/apidocs/) (now all in one place).
> - Check out the [OSLC 2020 Reference Implementation](https://github.com/oslc-op/refimpl) that uses Lyo 4.0 already! This is also a great time to take [Lyo Designer](https://oslc.github.io/developing-oslc-applications/eclipse_lyo/lyo-designer.html) for a spin and use it to study the models used to generate the majority of the reference implementation.

@jadelkhoury @jamsden will you please give me a hand with this? Feel free to edit the list below.

---

**TODOs**

- [ ] Update `oslc4j-client` references with `oslc-client`
- [ ] Mention availability on Maven Central and move SNAPSHOT repos onto a separate page (Participating in Lyo development, for example)
- [ ] Add a 4.0 migration page. See https://github.com/eclipse/lyo/issues/15
- [ ] Include oslc-java-client to oslc-client migration guide
- [ ] Highlight that legacy oslc-java-client is ONLY for use outside a JAX-RS server running Lyo 4.0, i.e. in ETL scripts and other Java SE apps.
- [ ] Introduce RootServicesHelper https://github.com/OSLC/lyo-samples/issues/38#issuecomment-725469102
- [ ] Introduce IOslcClient https://github.com/OSLC/lyo-samples/issues/38#issuecomment-725536578

**Comment by berezovskyi** [comment]
And now we have support for editing the site right from the browser if you are too lazy to check out the repo to fix a typo (you are not the main audience for this feature, it's more for regular Lyo users):

![Screenshot 2020-12-08 at 01 07 24](https://user-images.githubusercontent.com/64734/101420121-d5318c00-38f1-11eb-9e0d-8808bb5c9a46.png)

![Screenshot 2020-12-08 at 01 07 28](https://user-images.githubusercontent.com/64734/101420139-da8ed680-38f1-11eb-88f5-48a7e0d236d8.png)

**Comment by berezovskyi** [comment]
Also just added an ability to link to a heading directly:

![image](https://user-images.githubusercontent.com/64734/101421952-d369c780-38f5-11eb-9d3b-dadb6d49a0a0.png)

**Comment by berezovskyi** [comment]
added guides for migration all the way to Lyo 6
